options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  # Use the modern, required Node.js version
  - name: 'node:20'
    id: 'Install Dependencies'
    entrypoint: 'npm'
    args: ['ci']

  # Use the same Node.js version for the build
  - name: 'node:20'
    id: 'Build Application'
    entrypoint: 'npm'
    args: ['run', 'build']

  # And use the same Node.js version for the deployment
  - name: 'node:20'
    id: 'Deploy to Firebase'
    entrypoint: 'npm'
    args: ['run', 'deploy']