
# cloudbuild.yaml
# Cloud Build configuration file to build and deploy a Next.js app to Firebase Hosting  
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']

  - name: 'gcr.io/firebase-tools/firebase'
    args: ['deploy', '--only', 'hosting']
