steps:
  # Installs dependencies cleanly using package-lock.json
  - name: 'node:18'
    entrypoint: npm
    args: ['ci']

  # Builds the Next.js static site
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']

  # Deploys using the firebase-tools installed in node_modules
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'deploy']