steps:
  # Step 1: Install npm dependencies
  # This step uses a pre-built Docker image provided by the Cloud Build community
  # which contains Node.js and the npm package manager. It runs 'npm install'.
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  # Step 2: Build the Next.js production application
  # Using the same Node.js environment, this step runs the 'npm run build' script
  # which Next.js uses to create an optimized, production-ready version of our app.
  # The output is placed in the .next/ directory.
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']

  # Step 3: Deploy to Firebase Hosting
  # This step uses a special builder maintained by the Firebase community.
  # It contains the Firebase CLI and is authenticated to our project.
  # The 'deploy' command uploads the built assets to our live hosting URL.
  # The '--only hosting' flag ensures it only deploys hosting and nothing else.
  - name: 'gcr.io/firebase-tools/firebase'
    args: ['deploy', '--only', 'hosting']